= mdmm (Migration data manipulator & mapper)

Tools to work with migration data (metadata and objects) as produced by https://github.com/lyrasis/cdmtools/[cdmtools] and https://github.com/lyrasis/omeka-data-tools[omekatools]. Assumes the data formats, directory structures, and naming conventions used by those tools will be in place.

One tool to do the following, since these processes should be basically the same, regardless of source system.

- create CSV (one row per field per record, with raw field value) for profiling metadata field values in preparation for metadata mapping work
- automated metadata cleanup (via configurable find-replace)
- multivalued field splitting
- mapping JSON-based records to MODS
- moving/structuring/renaming metadata and object files to create Islandora-ready ingest directories

== Installation

Do `bundle install`

=== Configuration
The config file can become an extensive document which may include sensitive information.

It can also be an important record of your project and should be in a location that will be backed up regularly. 

*If you will only work on one project and/or don't plan on contributing code back to this repo...*
You can edit `config/config.yaml` in place to set up your project. When you run commands, this default config location will be used.

*If you will be working on multiple projects, need to keep your config(s) in a place where they can be backed up, or you want to avoid contributing your configs back to this repo...*

Copy `config/config.yaml` to your desired location and edit the copy. Specify the path to the desired config when you run a command, like this:

`exe/mdmm show_config --config=path/to/your/mdmm_config.yaml`

The example `config.yaml` included with the repo is heavily commented and intends to be self-documenting.

== Usage

For list of commands/functions:

`$ exe/mdmm help`

For details on what each command does:

`$ exe/mdmm help {command}` 

== License

The gem is available as open source under the terms of the [MIT License](https://opensource.org/licenses/MIT).
